// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://otqoucsjjrhregueocyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cW91Y3NqanJocmVndWVvY3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNjExNDQsImV4cCI6MjA3ODgzNzE0NH0.lNmyElZCin5Euh-Q2tGkvGMsQsN3PHB9XV2k6SSmiiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);